//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MyProto.proto
namespace ProtoTest
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestInfo")]
  public partial class TestInfo : global::ProtoBuf.IExtensible
  {
    public TestInfo() {}
    
    private string _test;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string test
    {
      get { return _test; }
      set { _test = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg")]
  public partial class Msg : global::ProtoBuf.IExtensible
  {
    public Msg() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ProtoTest.TestInfo _msg = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoTest.TestInfo msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private string _str = @"Test String";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"Test String")]
    public string str
    {
      get { return _str; }
      set { _str = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}